Import('qt_env')

env = qt_env.Clone()

env.EnableQtModules('Qml', 'Script','QuickWidgets')

env.AppendUnique(CPPDEFINES = [ 'INSTALLERBAIN_LIBRARY' ])

# Sigh
env['CPPPATH'] += [ '.' ]

env.Uic(env.Glob('*.ui'))

lib = env.SharedLibrary('installerBAIN', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
